# Generated by Django 3.2.9 on 2021-11-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=18)),
                ('Email', models.CharField(max_length=60)),
                ('Password', models.CharField(max_length=18)),
                ('Is_online', models.BooleanField(default=False)),
                ('List_of_friends', models.JSONField()),
                ('List_of_servers', models.JSONField()),
            ],
        ),
    ]
