# Generated by Django 3.2.9 on 2021-11-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('Server_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Server_name', models.CharField(max_length=18)),
                ('Admin', models.IntegerField()),
                ('List_of_Users', models.JSONField()),
                ('List_of_Channels', models.JSONField()),
            ],
        ),
    ]
